<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOAoyhhA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOAoyhhA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOAoyhhA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOAoyhhA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOAoyhhA\App_KernelDevDebugContainer([
    'container.build_hash' => 'OAoyhhA',
    'container.build_id' => '294d922d',
    'container.build_time' => 1714851236,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOAoyhhA');
